// Mocks generated by Mockito 5.4.3 from annotations
// in weight_tracker/test/presentation/screens/home/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weight_tracker/domain/models/failures.dart' as _i9;
import 'package:weight_tracker/domain/models/no_params.dart' as _i7;
import 'package:weight_tracker/domain/models/weight.dart' as _i6;
import 'package:weight_tracker/domain/usecases/delete_weight_usecase.dart'
    as _i8;
import 'package:weight_tracker/domain/usecases/get_weights_stream_usecase.dart'
    as _i3;
import 'package:weight_tracker/domain/usecases/sign_out_usecase.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWeightsStreamUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeightsStreamUseCase extends _i1.Mock
    implements _i3.GetWeightsStreamUseCase {
  MockGetWeightsStreamUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.QuerySnapshot<_i6.Weight>> execute(_i7.NoParams? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [input],
        ),
        returnValue: _i4.Stream<_i5.QuerySnapshot<_i6.Weight>>.empty(),
      ) as _i4.Stream<_i5.QuerySnapshot<_i6.Weight>>);
}

/// A class which mocks [DeleteWeightUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteWeightUseCase extends _i1.Mock
    implements _i8.DeleteWeightUseCase {
  MockDeleteWeightUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i9.Failure, void>> execute(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, void>>);
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i10.SignOutUseCase {
  MockSignOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i9.Failure, dynamic>> execute(_i7.NoParams? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [input],
        ),
        returnValue: _i4.Future<_i2.Either<_i9.Failure, dynamic>>.value(
            _FakeEither_0<_i9.Failure, dynamic>(
          this,
          Invocation.method(
            #execute,
            [input],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i9.Failure, dynamic>>);
}
